VentGram/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views
from posts import views
from iteractions import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('iteractions/', include(('iteractions.urls', 'iteractions'), namespace='iteractions')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iteractions/urls.py
#Django
from django.urls import path


#importaciones de apps
from iteractions import views


urlpatterns = [
        
    path(
        route='follow/<str:username>/<str:project_slug>/',
        view=views.follow,
        name='follow',
        ),

    path(
        route='unfollow/<str:username>/<str:project_slug>/',
        view=views.unfollow,
        name='unfollow',
        ),

    path(
        route='list_user/',
        view=views.UserListView,
        name='list_user',
        ),

    path(
        route='<int:project_id>/<str:project_slug>/',
        view=views.like,
        name='like_project'
        ),

    path(
        route='<int:post_id>/<int:position>',
        view=views.favorite,
        name='post_favorite'
        ),
        
    path(
        route='notification/',
        view=views.ShowNOtifications,
        name='notification'
        ),
    
    path(
        route='<noti_id>/delete',
        view=views.DeleteNotification,
        name='delete-notification'
        ),

    path(
        route='<int:comment_id>/<str:url>/delete',
        view=views.DeleteComments,
        name='delete-comments'
        ),

    path(
        route='messages/<str:username>',
        view=views.Inbox,
        name='messages'
        ),

    path(
        route='messages/directs/<username>',
        view=views.Directs,
        name='directs'
        ),

    path(
        route='messages/send/',
        view=views.SendDirect, 
        name='send-direct'
        ),

    path(
        route='messages/new/<username>',
        view=views.NewConversation, 
        name='newconversation'
        ),

    path(
        route='delete/<recipient>',
        view=views.DeleteConversation, 
        name='delete_conversation'
        ),

]

posts/urls.py
#Postss Urls

#Django
from django.urls import path


#importaciones de apps
from posts import views

urlpatterns = [

    #managment

    path(
        route='',
        view=views.PostHomeView,
        name='home'
        ),
        
    path(
        route='posts/',
        view=views.ProjectFeedView,
        name='feed'
        ),

    path(
        route='posts/projects',
        view=views.FilterProjectView,
        name='list_project'
        ),

    path(
        route='posts/create_project',
        view=views.CreatedProjectView.as_view(),
        name='new_project'
        ), 

    path(
        route='posts/<slug:url>/project1<int:project_id>48/',
        view=views.ProjectDetailView,
        name='detail_project'
        ),

    path(
        route='update_project/<slug:url>/',
        view=views.UpdateProjectView.as_view(),
        name='update_project'
        ),

    path(
        route='delete_project/<slug:url>/',
        view=views.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
        
]

users/urls.py
#Users Urls

#Django
from django.urls import path


#importaciones de apps
from users import views

urlpatterns = [

    #managment 
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login',
        ),
        
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout',
        ),

    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup',
        ),

    path(
        route='validate/',
        view=views.validate_token,
        name='validate_token',
        ),
    
    path(
        route='me/update_profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
        ),

    path(
        route='me/add_social_net/',
        view=views.UpdateSocialNet.as_view(),
        name='social_net'
        ),

    path(
        route='me/update_user/',
        view=views.UpdateUserView.as_view(),
        name='update_user'
        ),
        
    path(
        route='me/update_password/', 
        view=views.UserChangePasswordView.as_view(),
        name='change_password'
        ),

    path(
        route='me/delete_account/', 
        view=views.UserDelete.as_view(),
        name='delete_user'
        ),


    #profile
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    #Ajax
    path(
        route='ajax/provinces/',
        view=views.load_province,
        name='ajax_load_province'
    ),

        path(
        route='ajax/city/',
        view=views.load_city,
        name='ajax_load_city'
    ),

]

users/models/profile.py
#django
from django.db import models
from django.conf import settings

#utilities
from utils.models import CRideModel
from django.core import validators
from VentGram.validators import vcedula, SoloNumeros, SoloLetras


from users.models import User
from posts.models import Project
from iteractions.models import Relationship

def ruta(instance, file_name):
    route='{}/{}/{}/{}'.format( 'users',instance.user.email,'profile_picture',file_name)
    return route


class Profile(CRideModel):
    #profile model
    #extencio de proxy model mas informacion en la base de datos
    user=models.OneToOneField('users.User', on_delete=models.CASCADE,)
    country=models.ForeignKey('users.Country', on_delete=models.CASCADE, blank=True, null=True)
    province=models.ForeignKey('users.Province', on_delete=models.CASCADE, blank=True, null=True)
    city=models.ForeignKey('users.City', on_delete=models.CASCADE, blank=True, null=True)
    favorites = models.ManyToManyField(Project, related_name='favorites', blank=True)

    dni=models.CharField(max_length=10, validators=[validators.MinLengthValidator(10), vcedula], blank=True)
    gender=models.CharField(max_length=20, blank=True)
    birth_date=models.DateField(blank=True, null=True)
    biography=models.TextField(blank=True)
    phone_number=models.CharField(max_length=20, validators=[validators.MinLengthValidator(10), SoloNumeros], blank=True)
    education_level=models.CharField(max_length=50, blank=True)
    work_area=models.CharField(max_length=100, blank=True, validators=[validators.MinLengthValidator(4)], )
    home_address=models.CharField(max_length=100, blank=True)
    facebook=models.URLField(max_length=200, blank=True)
    twitter=models.URLField(max_length=200, blank=True)
    linkedin=models.URLField(max_length=200, blank=True)
    github=models.URLField(max_length=200, blank=True)
    
    picture=models.ImageField(
        upload_to=ruta,
        blank=True,
        null=True,)

    def __str__(self):
        #return username
        return str(self.user)
    
    def following(self):
	    user_ids = Relationship.objects.filter(from_user=self.user)\
							.values_list('to_user_id', flat=True)
	    return User.objects.filter(id__in=user_ids)


    def followers(self):
	    user_ids = Relationship.objects.filter(to_user=self.user)\
							.values_list('from_user_id', flat=True)
	    return User.objects.filter(id__in=user_ids)

templates/profile/city_dropdown_list.html
<option selected="true" disabled>Seleccione la Ciudad</option>
{% for city in citys %}
<option value="{{ city.id }}" >{{ city }}</option>
{% endfor %}

templates/profile/info_me_profile.html
{% load static %}
{% load humanize %}
<div class="main-left-sidebar">
    <div class="user_profile">
        <div class="user-pro-img mb-0">
            {% if user.profile.picture %}
            <img src="{{ user.profile.picture.url }}" alt="profile-image" width="200" height="200">
            {% else %}
            <div class="list-user" style="height: 200px;">
                <span style="width:200px; height: 200px; font-size: 100px; line-height: 198px;">{{user.first_name|first}}{{user.last_name|first}}</span>
            </div>
            {% endif %}
            {% if user == request.user %}
            <div class="add-dp" id="OpenImgUpload">
                <a href="{% url 'users:update_profile' %}" class="" ><i class="fas fa-user-edit"></i></a>
            </div>
            {% endif %}
        </div>
        <!--user-pro-img end-->
        <div class="user-specs  pt-1 pb-0 pl-3 pr-3">
            <h3>{{user.first_name}} {{user.last_name}}</h3>  
        </div>
        <div class="user-specs pb-3 pt-0">
            {% if user.profile.city %}
            <span><i class="fas fa-map-marker-alt pr-1" style="color:rgb(52, 216, 52);"></i> {{user.profile.city}}, {{user.profile.city.province.country}}</span>
            {% endif %}
        </div>
        <div class="user_pro_status pb-2">
            <ul class="flw-status">
                <li>
                    <span>Seguidos</span>
                    <b>{{ user.profile.following.count }}</b>
                </li>
                <li>
                    <span>Seguidores</span>
                    <b>{{ user.profile.followers.count }}</b>
                </li>
            </ul>
            {% if request.user.is_authenticated %}
            <ul class="flw-hr mt-2">
                {% if user != request.user %}
            
                {% if user not in request.user.profile.following %}
                    <li><a href="{% url 'iteractions:follow' user user.username %}" title="" class="flww"><i class="la la-plus"></i> Seguir</a></li>
                {% else %}
                    <li><a href="{% url 'iteractions:unfollow' user user.username %}" title="" class="flww"><i class="fas fa-check-circle"></i> Siguiendo</a></li>
                {% endif %}
                <li><a href="{% url 'iteractions:newconversation' user.username %}" title="" class="hre"><i class="far fa-envelope mr-1"></i>Mensaje</a></li>
                {% else %}
                <li><a href="{% url 'users:update_user' %}" title="Editar Usuario" class="flww"><i class="far fa-user mr-1"></i>Usuario</a></li>
                <li><a href="{% url 'users:update_profile' %}" title="Editar Perfil" class="hre"><i class="fas fa-user-edit mr-1"></i>Perfil</a></li>
                {% endif %}
            </ul>
            {% endif %}
            
            <ul>
                <li>
                    <p><i class="fas fa-clock mr-1"></i> Se unio {{ user.profile.created|naturaltime }}</p>
                </li>
                <li>
                    <p class="ml-1 text-capitalize"><i class="far fa-user  mr-1"></i>@{{ user.username }}</p>
                </li>
                <li>
                    {% if user.profile.phone_number %}
                    <p class="ml-1"><i class="fas fa-mobile-alt  mr-1"></i>{{ user.profile.phone_number }}</p>
                    {% endif %}
                </li>
                <li>
                    <p class="ml-1"><i class="fas fa-envelope  mr-1"></i>{{ user.email|capfirst}}</p>
                </li>
            </ul>
            {% if user ==  request.user %}
            <hr class="mb-0">
            {% else %}
            <hr>
            {% endif %}
        </div>
        
        <ul class="social_links">
            {% if user ==  request.user %}
            <li class="add-dpss mb-0 text-right" >
                <a href="{% url 'users:social_net' %}"><i class="fas fa-edit" style=" font-size: 15px;"></i></a>
            </li>
            {% endif %}
            <li class="add-dps">
             {% if  user.profile.facebook %}
                <a href="{{user.profile.facebook}}" target="_blank" ><i class="fab fa-facebook"></i></a>
             {% else %}
                <a><i class="fab fa-facebook" style="filter: grayscale();"></i></a>
             {% endif %}
             {% if  user.profile.twitter %}
                 <a href="{{user.profile.twitter}}" target="_blank"><i class="fab fa-twitter"></i></a>
             {% else %}
                <a><i class="fab fa-twitter" style="filter: grayscale();"></i></a>
             {% endif %}
             {% if  user.profile.linkedin %}
                 <a href="{{user.profile.linkedin}}" target="_blank"><i class="fab fa-linkedin-in" style="color: #0073b1;"></i></a>
             {% else %}
                <a><i class="fab fa-linkedin-in" style="filter: grayscale();"></i></a>
             {% endif %}
             {% if  user.profile.github %}
                 <a href="{{user.profile.github}}" target="_blank"><i class="fab fa-github" style="color:black;"></i></a>
             {% else %}
                <a><i class="fab fa-github" style="filter: grayscale();"></i></a>
             {% endif %}

            </li>

         </ul>
        <!--user_pro_status end-->
    </div>
    <!--user_profile end-->
</div>
<!--main-left-sidebar end-->

templates/profile/info_profile_public.html
{% load static %}
{% load humanize %}
<h6 style="font-weight: 600;">UN PROYECTO DE</h6>
<hr class="mt-2">
    <div class="user-data full-width">
        <div class="user-profile">
            <a href="{% url 'users:detail' project.user.username %}">
                <div class="usr-pic">
                {% if project.profile.picture %}
                    <img src="{{ project.profile.picture.url }}"  alt="profile-image" width="96" height="96">
                {% else %}
                    <div class="name-profile">
                        <span >{{project.user.first_name|first}}{{project.user.last_name|first}}</span>
                    </div>
                {% endif %}
                </div>
                
            <!--username-dt end-->
                <div class="user-specs pb-0">
                    <h3 class="mb-0">{{project.user.username}}</h3>
                </div>
                </a>
                    <div class="badges">
                        <span class="badge badge-info">{{project.profile.work_area}}</span>
                    </div>
                    <div class="user-specs py-0 ">
                        <h5 class="mb-0 py-1">En VentGram {{ project.profile.created|naturaltime }}</h5>
                    </div>
                    
                    {% if project.profile.city %}
                    <div class="user-specs pb-2 pt-0 ">
                        <span><i class="fas fa-map-marker-alt pr-1" style="color:rgb(52, 216, 52);"></i> {{project.profile.city}}, {{project.profile.country}}</span>
                    </div>
                    {% endif %}
            
        </div>
        
        <!--user-profile-->
        <div class="user_pro_status">
            <ul class="flw-status mt-1">
                {% if request.user.is_authenticated %}
                {% if project.user != request.user %}
                    {% if project.user not in request.user.profile.following %}
                    <a href="{% url 'iteractions:follow' project.user project.url %}" type="button" class="btn btn-secondary mb-2" style="padding: .175rem .55rem; font-size: 0.8rem;"><i class="fas fa-plus-circle mr-1"></i>Seguir</a>
                    {% else %}
                    <a href="{% url 'iteractions:unfollow' project.user project.url %}" type="button" class="btn btn-secondary mb-2" style="padding: .175rem .55rem; font-size: 0.8rem;"><i class="fas fa-check-circle mr-1"></i>Siguiendo</a>
                    {% endif %}
                <a href="{% url 'iteractions:newconversation' project.user.username %}" type="button" class="btn btn-danger mb-2" style="padding: .175rem .55rem; font-size: 0.8rem;"><i class="far fa-envelope mr-1"></i>Mensaje</a>
                {% endif%}
                {% endif %}
            </ul>
 
        </div>
        <!--user-profile-->
    </div>
<h6 style="font-weight: 600;">DETALLES</h6>
<hr class="mt-2">
<div class="user-specs py-2">
    <h5 style="font-weight: 600;">TITULO</h5>
    <h5>{{ project.title| upper }}</h5>
    <h5><img src="{% static 'img/clock.png' %}" alt="Fecha de publicacion" class="mr-1">{{ project.created|naturaltime }}</h5>
    <h5 style="font-weight: 600;" class="mt-3">CATEGORIA</h5>
    <h5>{{ project.category }}</h5>
    <h5 style="font-weight: 600;" class="mt-3">TIPO DE PROYECTO</h5>
    <h5>{{ project.typeProject }}</h5>
    <h5 style="font-weight: 600;" class="mt-3">TECNOLOGIAS UTILIZADAS</h5>
    <h5>{{ project.label }}</h5>
    <h5 style="font-weight: 600;" class="mt-3">ESTADO</h5>
    <h5>{{ project.status }}</h5>
</div>

templates/profile/profile.html
{% extends 'posts/base.html' %}
{% block head_content %}
Perfil | @{{user.username|capfirst}}
{% endblock%}
{% load static %}

{% block other_top %}
<!--agregar vistas al inicio sin ningun contenedor puesto -->
{% endblock %}

{% block row %}

    <div class="col-lg-3">
        {% include 'profile/info_me_profile.html' %}
        <!--right-sidebar end-->
    </div>
    <div class="col-lg-6">
        <div class="main-ws-sec">
            <div class="user-tab-sec rewivew">
                <div class="tab-feed st2 settingjb">
                    <ul>
                        <li data-tab="feed-dd" class="active">
                            <a href="#" title="">
                                <img src="{% static 'img/ic1.png'  %}" alt="">
                                <span>Inicio</span>
                            </a>
                        </li>
                        <li data-tab="info-dd">
                            <a href="#" title="Informacion">
                                <img src="{% static 'img/ic2.png'  %}" alt="">
                                <span>Infor</span>
                            </a>
                        </li>
                        <li data-tab="portfolio-dd">
                            <a href="#" title="">
                                <img src="{% static 'img/ic3.png'  %}" alt="">
                                <span>Portfolio</span>
                            </a>
                        </li>
                    </ul>
                    
                </div><!-- tab-feed end-->
            </div>

            <!--user-tab-sec end-->
            <div class="product-feed-tab current" id="feed-dd">
                {% if user == request.user %}
                <div class="post-topbar">
                    <div class="usy-dt">
                        {% if user.profile.picture %}
                        <img src="{{ user.profile.picture.url }}" alt="profile-image" width="40" height="40">
                        {% else %}
                        <a href="{% url 'users:detail' request.user.username %}" class="like-coms" type="button">
                            <span style="margin-top: 0px; width: 40px;height: 40px;padding-top: 4px;">{{request.user.first_name|first}}{{request.user.last_name|first}}</span>
                        </a>
                        {% endif %}
                    </div>
                    <div class="post-st mb-2 mt-2">
                        <ul>
                            <li><a href="{% url 'posts:new_project' %}" title="Añadir" class="active">
                                    <i class="fas fa-plus-square mr-2"></i>Añadir nuevo proyecto</a>
                            </li>
                        </ul>
                    </div>
                </div>
                {% endif %}

                {% if projects %}
                {% for project in projects %}
                    {% include 'posts/card_project.html' %}
                {% endfor %}
                    <div class="posts-section">
                        {% include 'pagination.html' %}   
                    </div>  
                {% else %}
                <div class="company-title" style="margin-top: -10px; margin-left: -14px;">
                    <h3 style="font-size: 25px;font-weight: 600; width: 106%;" >No tiene proyectos publicados</h3>
                </div>
                    
                {% endif %}
            </div>

            <!--product-feed-tab end-->
            <div class="product-feed-tab" id="info-dd">
                <!--user-profile-ov end-->
                <div class="user-profile-ov st2">
                    <h3>Datos
                        {% if user == request.user %}
                        <a href="{% url 'users:update_profile' %}" title="Personalizar Perfil"><i class="fa fa-pencil"></i></a></h3>
                        {% endif %}
                    <h4>Biografia</h4>
                    <p>{{user.profile.biography}}</p>   
                    <h4>Nivel Educativo</h4>
                    <p>{{ user.profile.education_level }}</p>
                    <h4>Telefono Celular</h4>
                    <p>{{ user.profile.phone_number }}</p>
                    <h4>Cedula</h4>
                    <p>{{ user.profile.dni }}</p>
                    <h4>Genero</h4>
                    <p>{{ user.profile.gender }}</p>
                    <h4>Ubicacion</h4>
                    <p>{{ user.profile.city }}</p>
                    <h4>Medio en el que labora</h4>
                    <p >{{ user.profile.work_area }}</p>
                    <h4>Direccion de casa</h4>
                    <p >{{ user.profile.home_address }}</p>
                </div>
                <!--user-profile-ov end-->

            </div>
            <!--product-feed-tab end-->

            <div class="product-feed-tab" id="portfolio-dd">
                <div class="portfolio-gallery-sec">
                    <h3 class="mb-0">Portfolio</h3>
                    {% if user == request.user %}
                    <div class="portfolio-btns">
                        <a href="{% url 'posts:new_project' %}" title="Crear Proyecto"><i class="fas fa-plus-square"></i> Añadir </a>
                    </div>
                    {% endif %}
                    <br><br>
                    <h3 class="mb-3 mt-3" >Favoritos</h3>
                    <div class="gallery_pf ">
                        <div class="row">
                            {% if favorites %}    
                                {% for favorite in favorites %} 
                                    <div class="col-lg-4 col-md-4 col-sm-6 col-6">
                                        <div class="gallery_pt">
                                            <div class="gallery_pt">
                                                <img src="{{ favorite.image.url }}" alt="">
                                                <a href="{% url 'posts:detail_project' favorite.url 0 %}" title="{{ favorite.title }}"><h3 style="color: aliceblue; padding: 15px; padding-top: 20px; font-size: 16px;">{{ favorite.title|slice:":40" }}</h3></a>
                                                {% if user == request.user %}
                                                    <div  class="cadidatesbtn">
                                                        <a title="Quitar"  href="{% url 'iteractions:post_favorite' favorite.id 0 %}"><i class="fas fa-trash-alt mr-1"></i></a> 
                                                    </div>
                                                {% endif %} 
                                            
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <h2 class="ml-1">No tiene favoritos agregados</h2>
                            {% endif %}
                        </div>
                    </div>
                    <h3 class="mb-3 mt-4" >Proyectos</h3>
                    <div class="gallery_pf mb-0">
                        <div class="row">
                            {% if  projectsPro %}
                                {% for project in projectsPro %}
                                <div class="col-lg-4 col-md-4 col-sm-6 col-6">
                                    
                                    <div class="gallery_pt">
                                        <img src="{{ project.image.url }}" alt="">

                                        <a href="{% url 'posts:detail_project' project.url 0 %}" title="{{project.title}}"><h3 style="color: aliceblue; padding: 15px; padding-top: 20px; font-size: 16px;">{{project.title|slice:":40"}}</h3></a>
                                        {% if user == request.user %}
                                            <div  class="cadidatesbtn">
                                                <a title="Editar"  href="{% url 'posts:update_project' project.url %}" ><i class="far fa-edit mr-1"></i></a> 
                                                <a title="Eliminar"  href="{% url 'posts:delete_project' project.url %}"><i class="fas fa-trash-alt mr-1"></i></a> 
                                            </div>
                                        
                                        {% endif %} 
                                    </div>
                                </div>
                                {% endfor %}
                            {% else %}
                            <h2 class="ml-1">No tiene proyectos agregados</h2>
                            {% endif %}
                    <!--gallery_pf end-->
                        </div>
                    </div>


                </div>
            </div>

        </div>
    </div>    
    <div class="col-lg-3">
        <div class="right-sidebar">
            <!--main-ws-sec
                <ul class="flw-status text-left">
                    <a href="{% url 'users:update_profile' %}" type="button" class="btn btn-danger mb-2" style="padding: .275rem .55rem; font-size: 0.8rem;"><i class="fas fa-user-edit mr-1"></i>Mensaje</a>
                </ul> --->
            <div class="widget widget-portfolio">
                <div class="wd-heady">
                    
                    <h3>Portfolio</h3>
                    <img src="{% static 'img/photo-icon.png' %}" alt="">
                </div>
                <div class="pf-gallery">
                    <ul>
                        {% for project in projectsPro %}
                        <li><a href="{% url 'posts:detail_project' project.url project.id %}" title=""><img src="{{ project.image.url }}" alt=""></a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <!--pf-gallery end-->
            </div>
            <!--widget-portfolio end-->
        </div>
    </div>


{% endblock%}
{% block other_button %}
<!--agregar vistas al final sin ningun contenedor puesto -->
{% endblock %}

templates/profile/province_dropdown_list.html
<option selected="true" disabled>Seleccione la Provincia</option>
{% for province in provinces %}
<option value="{{ province.id }}" >{{ province }}</option>
{% endfor %}

templates/profile/social_net.html
{% extends 'account_setting.html' %}
{% block head_content %}
Redes Sociales| @{{ user.username|capfirst }}
{% endblock%}
{% block redes %}
<div class="acc-setting">
    <h3>Redes Sociales</h3>
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
      <div class="row notbar" >
        <div class="col-lg-12">
            {% if form.errors %}
                <div class="alert alert-danger alert-dismissible show">   
                    Introduzca una URL valida
                </div>
            {% endif %}
        </div>
        
        <div class="col-sm-12 col-md-6">
            <h4>Facebook</h4>
            <div class="form-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fab fa-facebook "></i></span>
                    <input
                        class="{% if form.facebook.errors %}is-invalid{% endif %} form-control" 
                        type="text" name="facebook" placeholder="Coloque la Url de su cuenta de Facebook "
                        value="{% if form.errors %}{{form.facebook.value }}{% else %}{{ user.profile.facebook }}{% endif %}" />
                </div>
                <div class="invalid-feedback">
                    {% for error in form.facebook.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            </div>

        </div>
        <div class="col-sm-12 col-md-6">
            <h4>Twitter</h4>
            <div class="form-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fab fa-twitter "></i></span>
                    <input 
                    class="{% if form.twitter.errors %}is-invalid{% endif %} form-control" 
                    type="text" name="twitter" placeholder="Coloque la Url de su cuenta de Twitter "
                    value="{% if form.errors %}{{form.twitter.value }}{% else %}{{ user.profile.twitter }}{% endif %}">
                </div>
                <div class="invalid-feedback">
                    {% for error in form.twitter.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
            </div>
        </div>
        
        <div class="col-sm-12 col-md-6 ">
            <h4>Linkedin</h4>
            <div class="form-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fab fa-linkedin-in"></i></span>
                    <input class="{% if form.linkedin.errors %}is-invalid{% endif %} form-control"
                    type="text"  name="linkedin" placeholder="Coloque la Url de su cuenta de Linkedin "
                    value="{% if form.errors %}{{form.linkedin.value }}{% else %}{{ user.profile.linkedin }}{% endif %}">
                </div>
                <div class="invalid-feedback">
                    {% for error in form.linkedin.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-6 ">
            <h4>GitHub</h4>
            <div class="form-group">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1"><i class="fab fa-github"></i></span>
                    <input 
                    class="{% if form.github.errors %}is-invalid{% endif %} form-control"
                    type="text"  name="github" placeholder="Coloque la Url de su cuenta de Github "
                    value="{% if form.errors %}{{form.github.value }}{% else %}{{ user.profile.github }}{% endif %}">
                </div>
                <div class="invalid-feedback">
                    {% for error in form.github.errors %}
                    {{ error }}
                    {% endfor %}
                </div>
            </div>
        </div>
       
      
    <div class="save-stngs pd2">
        <ul>
            <li><button type="submit">Guardar</button>
                <a class="btn btn-danger mb-1 pb-2 ml-2" href="{% url 'users:social_net' %}">
                    Cancelar
                </a></li>
        </ul>
    </div>
</div> 
      </form>
      
      <!--notifications-list end-->
  </div><!--acc-setting end-->
{% endblock %}