VentGram/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views
from posts import views
from iteractions import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('iteractions/', include(('iteractions.urls', 'iteractions'), namespace='iteractions')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iteractions/urls.py
#Django
from django.urls import path


#importaciones de apps
from iteractions import views


urlpatterns = [
        
    path(
        route='follow/<str:username>/<str:project_slug>/',
        view=views.follow,
        name='follow',
        ),

    path(
        route='unfollow/<str:username>/<str:project_slug>/',
        view=views.unfollow,
        name='unfollow',
        ),

    path(
        route='list_user/',
        view=views.UserListView,
        name='list_user',
        ),

    path(
        route='<int:project_id>/<str:project_slug>/',
        view=views.like,
        name='like_project'
        ),

    path(
        route='<int:post_id>/<int:position>',
        view=views.favorite,
        name='post_favorite'
        ),
        
    path(
        route='notification/',
        view=views.ShowNOtifications,
        name='notification'
        ),
    
    path(
        route='<noti_id>/delete',
        view=views.DeleteNotification,
        name='delete-notification'
        ),

    path(
        route='<int:comment_id>/<str:url>/delete',
        view=views.DeleteComments,
        name='delete-comments'
        ),

    path(
        route='messages/<str:username>',
        view=views.Inbox,
        name='messages'
        ),

    path(
        route='messages/directs/<username>',
        view=views.Directs,
        name='directs'
        ),

    path(
        route='messages/send/',
        view=views.SendDirect, 
        name='send-direct'
        ),

    path(
        route='messages/new/<username>',
        view=views.NewConversation, 
        name='newconversation'
        ),

    path(
        route='delete/<recipient>',
        view=views.DeleteConversation, 
        name='delete_conversation'
        ),

]

posts/urls.py
#Postss Urls

#Django
from django.urls import path


#importaciones de apps
from posts import views

urlpatterns = [

    #managment

    path(
        route='',
        view=views.PostHomeView,
        name='home'
        ),
        
    path(
        route='posts/',
        view=views.ProjectFeedView,
        name='feed'
        ),

    path(
        route='posts/projects',
        view=views.FilterProjectView,
        name='list_project'
        ),

    path(
        route='posts/create_project',
        view=views.CreatedProjectView.as_view(),
        name='new_project'
        ), 

    path(
        route='posts/<slug:url>/project1<int:project_id>48/',
        view=views.ProjectDetailView,
        name='detail_project'
        ),

    path(
        route='update_project/<slug:url>/',
        view=views.UpdateProjectView.as_view(),
        name='update_project'
        ),

    path(
        route='delete_project/<slug:url>/',
        view=views.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
        
]

users/urls.py
#Users Urls

#Django
from django.urls import path


#importaciones de apps
from users import views

urlpatterns = [

    #managment 
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login',
        ),
        
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout',
        ),

    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup',
        ),

    path(
        route='validate/',
        view=views.validate_token,
        name='validate_token',
        ),
    
    path(
        route='me/update_profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
        ),

    path(
        route='me/add_social_net/',
        view=views.UpdateSocialNet.as_view(),
        name='social_net'
        ),

    path(
        route='me/update_user/',
        view=views.UpdateUserView.as_view(),
        name='update_user'
        ),
        
    path(
        route='me/update_password/', 
        view=views.UserChangePasswordView.as_view(),
        name='change_password'
        ),

    path(
        route='me/delete_account/', 
        view=views.UserDelete.as_view(),
        name='delete_user'
        ),


    #profile
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    #Ajax
    path(
        route='ajax/provinces/',
        view=views.load_province,
        name='ajax_load_province'
    ),

        path(
        route='ajax/city/',
        view=views.load_city,
        name='ajax_load_city'
    ),

]

posts/models/category.py
#django
from django.db import models

#utilities
from utils.models import CRideModel
from users.models import User

#validators
from django.core import validators
from VentGram.validators import SoloNumeros


def ruta_imagen_Category(instance, file_name):
    route='{}/{}/{}'.format( 'category', instance.category, file_name)
    return route

def ruta_imagen_type(instance, file_name):
    route='{}/{}/{}'.format( 'type', instance.TypeProject, file_name)
    return route

def ruta_imagen_Status(instance, file_name):
    route='{}/{}/{}'.format( 'status', instance.status, file_name)
    return route
class Category(CRideModel):
    #profile model
    #extencio de proxy model mas informacion en la base de datos
    category=models.CharField(max_length=60, validators=[validators.MinLengthValidator(5)])
    image=models.ImageField(upload_to=ruta_imagen_Category)
    

    def __str__(self):
        #return username
        return str(self.category)

class TypeProject(CRideModel):
    #profile model
    #extencio de proxy model mas informacion en la base de datos
    TypeProject=models.CharField(max_length=60, validators=[validators.MinLengthValidator(5)])
    image=models.ImageField(upload_to=ruta_imagen_type)

    def __str__(self):
        #return username
        return str(self.TypeProject)

class Status(CRideModel):
    #profile model
    #extencio de proxy model mas informacion en la base de datos
    status=models.CharField(max_length=30, validators=[validators.MinLengthValidator(5)])
    image=models.ImageField(upload_to=ruta_imagen_Status)

    def __str__(self):
        #return username
        return str(self.status)

posts/models/project.py
#django
from django.db import models
from django.utils.text import slugify


#utilities
from utils.models import CRideModel
from users.models import User
from posts.models import Category, Status, TypeProject

#validators
from django.core import validators
from VentGram.validators import SoloNumeros

def ruta_imagen(instance, file_name):
    route='{}/{}/{}/{}/{}'.format( 'users', instance.user.email, 'projects','img', file_name)
    return route

def ruta_documento(instance, file_name):
    route='{}/{}/{}/{}/{}'.format( 'users', instance.user.pk, 'projects', 'document   ', file_name)
    return route


class Project(CRideModel):
    #profile model
    #extencio de proxy model mas informacion en la base de datos
    user=models.ForeignKey(User, on_delete=models.CASCADE,)
    profile= models.ForeignKey('users.profile', on_delete=models.CASCADE,)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    typeProject=models.ForeignKey(TypeProject, on_delete=models.CASCADE)
    status=models.ForeignKey(Status, on_delete=models.CASCADE)

    title=models.CharField('titulo',max_length=300)
    description=models.TextField(validators=[validators.MinLengthValidator(125)])
    objetive=models.TextField(validators=[validators.MinLengthValidator(15)])
    image=models.ImageField(upload_to=ruta_imagen)
    label=models.CharField(max_length=100, validators=[validators.MinLengthValidator(3)])
    website=models.URLField(max_length=200, blank=True)
    document=models.FileField(upload_to=ruta_documento)
    collaborators=models.CharField(max_length=300, validators=[validators.MinLengthValidator(5)], blank=True)
    url = models.SlugField(max_length=255, unique=True)
    likes = models.IntegerField(default=0, blank=True, null=True)
    views=models.IntegerField(default=0, blank=True, null=True)
    count_comments=models.IntegerField(default=0, blank=True, null=True)


    def save(self, *args, **kwargs):
        if not self.url:
            project=Project.objects.first()
            if project is int:
                pk=project.pk
                pk+=1
            else:
                pk=1
            cadena = slugify(self.user)+slugify(pk)+'-'+slugify(self.title)
            while Project.objects.filter(url=cadena).exists():
                pk+=1
                cadena = slugify(self.user)+slugify(pk)+'-'+slugify(self.title)
            self.url=cadena
        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return '{} por @{}'.format(self.title, self.user.username)

posts/forms.py
#Django
from django import forms

#Models
from posts.models import Project
from VentGram.validators import SoloLetras


class ProjectForm(forms.ModelForm):
    
    STATUS_CHOICES=("Iniciado", "En Proceso", "Finalizado")
    class Meta:
        model=Project
        fields=[
            'user', 
            'profile',
            'category',
            'title',
            "label",
            'description', 
            'objetive',
            'image',
            'status',
            'typeProject',
            'website',
            'document',
            'collaborators',
            'views',
            ]
    def clean_title(self):
        title=self.cleaned_data['title'].capitalize()
        return title

    def clean_collaborators(self):
        collaborators=self.cleaned_data['collaborators'].title()
        SoloLetras(collaborators, 'Colaboradores')
        return collaborators

    def clean_objetive(self):
        objetive=self.cleaned_data['objetive'].capitalize() 
        return objetive
            
    widgets = {
        'category': forms.Select(attrs={'class': 'form-control'}),
        'typeProject': forms.Select(attrs={'class': 'form-control'}),
        'status': forms.Select(attrs={'class': 'form-control'}),
    }

posts/views.py
#Django
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, ListView, TemplateView, CreateView, DetailView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.core.paginator import Paginator

#models
from iteractions.models import Likes, Comment
from users.models import Profile, User
from posts.models import Project, Category, Status, TypeProject

#python
import time
#forms
from posts.forms import ProjectForm
from iteractions.forms import CommentForm


@login_required
def FilterProjectView(request):
    busqueda = request.POST.get("buscar")
    filtroCa=request.POST.get("filtroCategoria")
    filtroEs=request.POST.get("filtroEstado")
    filtroTy=request.POST.get("filtroType")
    projects = Project.objects.all()
    categorys = Category.objects.all()
    typeProject=TypeProject.objects.all()
    status = Status.objects.all()
    context=()
    if busqueda:
        projects = Project.objects.filter(
            Q(title__icontains = busqueda) |  
            Q(description__icontains = busqueda) 
        ).distinct()
    elif filtroCa:
        projects = Project.objects.filter(category=filtroCa)
        context=('Proyectos de categoria ')
    elif filtroEs:
        context=('Proyectos con estado ')
        projects = Project.objects.filter(status=filtroEs)
    elif filtroTy:
        context=('Proyectos de tipo ')
        projects = Project.objects.filter(typeProject=filtroTy)
    
        

    paginator=Paginator(projects, 6)
    page=request.GET.get('page')
    projects=paginator.get_page(page)
    return render(request, 'posts/list_project.html', {'projects':projects, 'categorys':categorys, 'statuss':status, 'context':context, 'types':typeProject})

@login_required
def ProjectFeedView(request,**kwargs):
    busqueda = request.POST.get("buscar")
    projects = Project.objects.all()
    if busqueda:
        projects = Project.objects.filter(
            Q(title__icontains = busqueda) | 
            Q(description__icontains = busqueda) 
        ).distinct()

    paginator=Paginator(projects, 9)
    page=request.GET.get('page')
    projects=paginator.get_page(page)
    return render(request, 'posts/feed.html', {'projects':projects})

@login_required
def ProjectDetailView(request, url, project_id):
    project= get_object_or_404(Project, url=url)
    user= request.user
    profile= Profile.objects.get(user=user)
    favorited= False

    projects = Project.objects.get(url=url)
    if project_id != 0:
        if projects.user != user:
            views=projects.views+1
            Project.objects.filter(url=url).update(views=views)

    #like
    
    is_like= Likes.objects.filter(user=user, post=project).exists()

    #comment
    comments = Comment.objects.filter(post=project).order_by('date')

    if request.user.is_authenticated:
        profile= Profile.objects.get(user=user)

        if profile.favorites.filter(url=url).exists():
            favorited=True

	#Comments Form
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = project
            comment.user = user
            comment.save()
            count=projects.count_comments+1
            Project.objects.filter(url=url).update(count_comments=count)
            return HttpResponseRedirect(reverse('posts:detail_project', args=[url, 0]))	
    else:
        form = CommentForm()
    
    template = loader.get_template('posts/detail_project.html')
    context = {
        'project':project,
		'favorited':favorited,
		'profile':profile,
        'form':form,
        'comments':comments,
        'likes':is_like,
    }
    return HttpResponse(template.render(context, request))

class CreatedProjectView(LoginRequiredMixin, CreateView):
    #Crear un nuevo post
    template_name='posts/create_update_project.html'
    form_class=ProjectForm
    success_url=reverse_lazy('posts:feed')

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['user']=self.request.user
        context['profile']=self.request.user.profile
        return context
  
class UpdateProjectView(LoginRequiredMixin, UpdateView):
    #Crear un nuevo post
    template_name='posts/create_update_project.html'
    model=Project
    form_class=ProjectForm
    slug_field = 'url'
    slug_url_kwarg = 'url'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['user']=self.request.user
        context['profile']=self.request.user.profile
        return context
        
    def get_success_url(self):
        #Return to users profile.
        username=self.object.user.username
        return reverse('users:detail', kwargs={'username':username})


class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model=Project
    slug_field = 'url'
    slug_url_kwarg = 'url'

    def get_success_url(self):
        #Return to users profile.
        username=self.object.user.username
        return reverse('users:detail', kwargs={'username':username})

def PostHomeView(request,**kwargs):
    projects = Project.objects.all()
    paginator=Paginator(projects, 6)
    page=request.GET.get('page')
    projects=paginator.get_page(page)
    return render(request, 'home.html', {'projects':projects})

templates/posts/detail_project.html
{% extends 'posts/base.html' %}
{% load humanize %}
{% load static %}
{% block head_content %}
   project | VentGram
{% endblock%}

    {% block other_top %}
    {% endblock %}
        {% block row %}
        <div class="col-lg-5 col-md-7 pd-left-none">
            <div class="usy-dt">
                {% if request.user.profile.picture %}
                    <img src="{{ user.profile.picture.url }}"  alt="profile-image" width="40" height="40">
                {% else %}
                <a href="{% url 'users:detail' request.user.username %}" class="like-coms" type="button">
                    <span style="margin-top: 0px; width: 40px;height: 40px;padding-top: 4px;">{{request.user.first_name|first}}{{request.user.last_name|first}}</span>
                </a>
                {% endif %}
                </div>
            <div class="post-st mb-3">
                <ul>
                    <li><a href="{% url 'posts:new_project' %}" title=""><i class="far fa-plus-square mr-2"></i>Añadir nuevo proyecto</a>
                    </li>
                </ul>
            </div>
            <!--post-st end-->
        </div>
         <div class="col-lg-9 col-md-9 pd-left-none">
            <div class="main-ws-sec">
                <div class="posts-section">
                    <div class="box gallery_pt">
                        
                        <img src="{{ project.image.url }}" class="">
                        <a href="" title=""><h3 style="color: aliceblue; padding: 15px; padding-top: 25px;font-size: 22px;font-weight: 600;">{{ project.title }}</h3></a>
                    </div>
                    <div class="post-bar" style="height: 100%;">

                        <div class="user-specs pt-0 pb-0">
                            
                            <div class="ed-opts">
                                <a href="#" title="" class="ed-opts-open"><i class="la la-ellipsis-v"></i></a>
                                <ul class="ed-options" style="width: 160px;">

                                    {% if project.profile.user == request.user %}
                                        {% if favorited %}
                                            <li><a href="{% url 'iteractions:post_favorite' project.id 1 %}" title="" style="text-transform: none;">Quitar de favoritos</a></li>
                                        {% else %}
                                            <li><a href="{% url 'iteractions:post_favorite' project.id 1 %}" title="" style="text-transform: none;">Agregar a favoritos</a></li>
                                        {% endif %}
                                        <li><a href="{% url 'posts:update_project' project.url %}" title="Editar">Editar</a></li>
                                        <li><a href="{% url 'posts:delete_project' project.url %}" title="Eliminar">Eliminar</a></li>

                                    {% else %}
                                        {% if favorited %}
                                            <li><a href="{% url 'iteractions:post_favorite' project.id 1 %}" title="">Quitar de Favoritos</a></li>
                                        {% else %}
                                            <li><a href="{% url 'iteractions:post_favorite' project.id 1 %}" title="">Agregar a Favoritos</a></li>
                                        {% endif %}
                                    {% endif %}

                                </ul>
                            </div>
                            
                            <h3 style="text-transform:none">{{ project.title }}</h3>
                            <a href="{% url 'users:detail' project.user.username %}">Por: {{project.user.first_name }} {{project.user.last_name}} | @{{project.user.username }}</a>
                            {% if project.collaborators %}
                            <h4 class="pt-1">colaboradores: {{ project.collaborators }}</h4>
                            {% endif %}
                            <hr>
                        </div>
                        <div class="job_descp accountnone">
                            <h3>Objetivo</h3>
                            <p>{{ project.objetive|linebreaksbr}}</p>
                                <hr>
                            <h3>Descripcion</h3>
                            <p>{{ project.description|linebreaksbr }}</p>  
                        </div>
                        
                        <div class="user_pro_status">
                            <hr>
                            <h3 class="mb-3" style="font-weight: 600;">Documento</h3>
                            <div class="row box_document_detail">

                                <div class="col-lg-9 col-md-8 col-sm-8">
                                    <h5 class="mt-3"><i class="fas fa-file-alt mr-2"></i>{{ project.document.name|slice:"25:"}}</h5> 
                                </div>
                                <div class="col-lg-3 col-md-4 col-sm-4 text-right">
                                    <a href="{{ project.document.url }}" target="_blank" title="DESCARGAR: {{ project.document.name|slice:'25:'}}" type="button" class="btn btn-danger mt-2 mb-2 text-center"style="padding: .275rem .55rem; font-size: 0.8rem;width: 100%; color:white ;"><i class="fas fa-download mr-1"></i>Descargar</a>
                                </div>
                            </div>  
                        </div>
                        <div class="job-status-bar btm-line mt-4">                                               
                           <ul class="like-com">
                                <li>
                                    {% if likes %}
                                    <a href="{% url 'iteractions:like_project' project.id project.url %}" class="active"><i class="fas fa-heart"></i> Me gusta  {{project.likes}}</a>
                                    {% else %}
                                    <a href="{% url 'iteractions:like_project' project.id project.url %}"><i class="fas fa-heart"></i> Me gusta  {{project.likes}}</a>
                                    {% endif %}
                                    
                                </li>
                                <li>
                                    {% if project.count_comments != 0 %}
                                    <a class="mt-3" style="color: rgb(39, 145, 231);"><i class="fas fa-comment-alt"></i> Comentarios {{project.count_comments}}</a>
                                    {% else %}
                                    <a class="mt-3" style="color: rgba(141, 141, 141, 0.726);"><i class="fas fa-comment-alt"></i> Comentarios {{project.count_comments}}</a>
                                    {% endif %}
                                </li>
                                <li>
                                    {% if comments %}
                                    <a class="mt-3" style="color: rgb(49, 209, 57);"><i class="fas fa-eye" style="font-size: 16px;"></i> Vistas {{ project.views }}</a>
                                    {% else %}
                                    <a class="mt-3" style="color: rgba(141, 141, 141, 0.726);"><i class="fas fa-eye" style="font-size: 16px;"></i> Vistas {{ project.views }}</a>
                                    {% endif %}  
                                </li>
                                <li>
                                    {% if favorited %}
                                        <a class="mt-3" href="{% url 'iteractions:post_favorite' project.id 1 %}" style="color: rgb(214, 21, 21);"><i class="fas fa-minus-circle" style="font-size: 16px;"></i> Quitar de favoritos</a>
                                    {% else %}
                                        <a class="mt-3" href="{% url 'iteractions:post_favorite' project.id 1 %}" style="color: rgb(19, 152, 175);"><i class="fas fa-plus-circle" style="font-size: 16px;"></i> Guardar en favoritos</a>
                                    {% endif %}
                                </li>
                            </ul>
                                                                   
                        </div>

                        {% if comments %}
                        <div class="text-left">
                            <h3 style="font-size: 20px; font-weight: 600;margin-bottom: 20px;">Comentarios</h3>
                        </div>
                        {% endif %}
                        <div class="comment-area ">
                            {% for comment in comments %}
                            <div class="post_topbar">
                                {% if comment.user == request.user %}
                                <div class="ed-opts pr-3 pt-3">
                                    <a href="#" title="" class="ed-opts-open"><i class="la la-ellipsis-v"></i></a>
                                    <ul class="ed-options">
                                        <li><a href="{% url 'iteractions:delete-comments' comment.id project.url %}" title="Eliminar">Eliminar</a>
                                        </li>
                                    </ul>
                                </div>
                                {% endif %}
                                <div class="usy-dt pl-3 pt-3">
                                    {% if comment.user.profile.picture %}
                                    <a href="{% url 'users:detail' comment.user.username %}"><img src="{{ comment.user.profile.picture.url }}" alt="profile-image" width="37" height="37"></a>
                                    {% else %}
                                    <a href="{% url 'users:detail' comment.user.username %}" class="like-coms ml-1 pd-right-none" >
                                        <span class="mt-0">{{comment.user.first_name|first}}{{comment.user.last_name|first}}</span>
                                    </a>
                                    {% endif %}
                                </div>
                                <div class="container-comment pt-3">
                                    <div class="comment ml-2">
                                        <h3 class="mb-1" >{{comment.user.first_name}} {{comment.user.last_name }}</h3>
                                        <span class="mb-1"><img src="{% static 'img/clock.png' %} ">{{comment.date|naturaltime}}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="container-comment pl-3 pr-3">
                                <div class="reply-area mb-3">
                                    <p style="font-size: 17px;">{{comment.body|capfirst}} </p> 
                                </div> 
                            </div>


                            {% endfor %}
                        </div>
                        <div class="text-left mt-5">
                            <h3 style="font-size: 20px; font-weight: 600;margin-bottom: 20px;">Agregar Comentario</h3>
                        </div>
                        <div>
                            <form method="post" action="" role="form">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-1 col-md-2 col-sm-12 mb-3 pd-left-none ">
                                        <div class="usy-dt">
                                            {% if request.user.profile.picture %}
                                            <a  href="{% url 'users:detail' request.user.username %}">
                                                <img src="{{ request.user.profile.picture.url }}" alt="profile-image" width="50" height="50">
                                            </a>
                                            {% else %}
                                            <a  href="{% url 'users:detail' request.user.username %}" class="like-coms mt-0 ml-1 pd-right-none" >
                                                <span style="width: 50px; height: 50px; border-radius:40px; margin-top: -16px;line-height: 42px; font-size: 26px;">{{request.user.first_name|first}}{{request.user.last_name|first}}</span>
                                            </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                    
                                    <div class="col-lg-8 col-md-10 col-sm-12 pd-left-none">                             
                                        <form>
                                            <div class="form-group ">
                                                <textarea  type="text" name="body" class="form-control" placeholder="Escribir un comentario" rows="5" required></textarea>
                                            </div>
                                        </form>
                                    </div>
        
                                    <div class="col-lg-3 col-md-12 col-sm-12 pd-left-none mt-1">
                                        <button type="submit" name="action" class="btn btn-info" style="width: 100%;"><i class="fas fa-comment-alt mr-2"></i>Enviar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <!--post-bar end-->
            </div>
         </div>
         <div class="col-lg-3 col-md-3 pd-right-none">
            {% include 'profile/info_profile_public.html' %}
        </div>             
        {% endblock %}

    {% block other_button %}
    {% endblock %}

templates/posts/nav.html
{% load static %}
<nav id="header" class="navbar navbar-expand-lg navbar-dark py-0">
    <div class="container">
      <a href="{% url 'posts:home' %}">
        <img src="{% static "img/Logo.png" %}" alt="VentGram" loading="lazy">
          
      </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01" >
          <ul class="text-nav navbar-nav ml-auto mt-2 mt-lg-0 ">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'posts:home' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.youtube.com/channel/UCoOqccgdZwG7VzXJV8bbtHA?view_as=subscriber">Canal Youtube</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Lugares</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-donaciones " href="#">Donaciones</a>
            </li>
          </ul>
          <a href="{% url 'users:login' %}" type="button" class="btn btn-suscribe"><i class="far fa-user"></i> Inicar Sesion</a>
        </div>
      </div>
</nav>