VentGram/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views
from posts import views
from iteractions import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('iteractions/', include(('iteractions.urls', 'iteractions'), namespace='iteractions')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iteractions/urls.py
#Django
from django.urls import path


#importaciones de apps
from iteractions import views


urlpatterns = [
        
    path(
        route='follow/<str:username>/<str:project_slug>/',
        view=views.follow,
        name='follow',
        ),

    path(
        route='unfollow/<str:username>/<str:project_slug>/',
        view=views.unfollow,
        name='unfollow',
        ),

    path(
        route='list_user/',
        view=views.UserListView,
        name='list_user',
        ),

    path(
        route='<int:project_id>/<str:project_slug>/',
        view=views.like,
        name='like_project'
        ),

    path(
        route='<int:post_id>/<int:position>',
        view=views.favorite,
        name='post_favorite'
        ),
        
    path(
        route='notification/',
        view=views.ShowNOtifications,
        name='notification'
        ),
    
    path(
        route='<noti_id>/delete',
        view=views.DeleteNotification,
        name='delete-notification'
        ),

    path(
        route='<int:comment_id>/<str:url>/delete',
        view=views.DeleteComments,
        name='delete-comments'
        ),

    path(
        route='messages/<str:username>',
        view=views.Inbox,
        name='messages'
        ),

    path(
        route='messages/directs/<username>',
        view=views.Directs,
        name='directs'
        ),

    path(
        route='messages/send/',
        view=views.SendDirect, 
        name='send-direct'
        ),

    path(
        route='messages/new/<username>',
        view=views.NewConversation, 
        name='newconversation'
        ),

    path(
        route='delete/<recipient>',
        view=views.DeleteConversation, 
        name='delete_conversation'
        ),

]

posts/urls.py
#Postss Urls

#Django
from django.urls import path


#importaciones de apps
from posts import views

urlpatterns = [

    #managment

    path(
        route='',
        view=views.PostHomeView,
        name='home'
        ),
        
    path(
        route='posts/',
        view=views.ProjectFeedView,
        name='feed'
        ),

    path(
        route='posts/projects',
        view=views.FilterProjectView,
        name='list_project'
        ),

    path(
        route='posts/create_project',
        view=views.CreatedProjectView.as_view(),
        name='new_project'
        ), 

    path(
        route='posts/<slug:url>/project1<int:project_id>48/',
        view=views.ProjectDetailView,
        name='detail_project'
        ),

    path(
        route='update_project/<slug:url>/',
        view=views.UpdateProjectView.as_view(),
        name='update_project'
        ),

    path(
        route='delete_project/<slug:url>/',
        view=views.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
        
]

users/urls.py
#Users Urls

#Django
from django.urls import path


#importaciones de apps
from users import views

urlpatterns = [

    #managment 
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login',
        ),
        
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout',
        ),

    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup',
        ),

    path(
        route='validate/',
        view=views.validate_token,
        name='validate_token',
        ),
    
    path(
        route='me/update_profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
        ),

    path(
        route='me/add_social_net/',
        view=views.UpdateSocialNet.as_view(),
        name='social_net'
        ),

    path(
        route='me/update_user/',
        view=views.UpdateUserView.as_view(),
        name='update_user'
        ),
        
    path(
        route='me/update_password/', 
        view=views.UserChangePasswordView.as_view(),
        name='change_password'
        ),

    path(
        route='me/delete_account/', 
        view=views.UserDelete.as_view(),
        name='delete_user'
        ),


    #profile
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    #Ajax
    path(
        route='ajax/provinces/',
        view=views.load_province,
        name='ajax_load_province'
    ),

        path(
        route='ajax/city/',
        view=views.load_city,
        name='ajax_load_city'
    ),

]

iteractions/models/comment.py
from django.db import models
from posts.models import Project
from users.models import User 
from iteractions.models import Notification

from django.db.models.signals import post_save, post_delete

class Comment(models.Model):
	post = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='comments')
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	def user_comment_post(sender, instance, *args, **kwargs):
		comment = instance
		post = comment.post
		text_preview = comment.body[:90]
		sender = comment.user
		if post.user != sender:
			notify = Notification(post=post, sender=sender, user=post.user, text_preview=text_preview ,notification_type=2)
			notify.save()

	def user_del_comment_post(sender, instance, *args, **kwargs):
		like = instance
		post = like.post
		sender = like.user

		notify = Notification.objects.filter(post=post, sender=sender, notification_type=2)
		notify.delete()

#Comment
post_save.connect(Comment.user_comment_post, sender=Comment)
post_delete.connect(Comment.user_del_comment_post, sender=Comment)

iteractions/models/follow.py
from django.db import models
from users.models import User

from iteractions.models import Notification


class Relationship(models.Model):
	from_user = models.ForeignKey(User, related_name='relationships', on_delete=models.CASCADE)
	to_user = models.ForeignKey(User, related_name='related_to', on_delete=models.CASCADE)
	
	def __str__(self):
		return f'{self.from_user} to {self.to_user}'

	class Meta:
		indexes = [
		models.Index(fields=['from_user', 'to_user',]),
        ]

iteractions/models/likes.py
#Django
from django.db import models
from django.db.models.signals import post_save, post_delete

#models
from users.models import User
from posts.models import Project
from iteractions.models import Notification

class Likes(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')
	post = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='post_like')
    
	def user_liked_post(sender, instance, *args, **kwargs):
		like = instance
		post = like.post
		sender = like.user
		if post.user != sender:
			notify = Notification(post=post, sender=sender, user=post.user, notification_type=1)
			notify.save()
	
	def user_unlike_post(sender, instance, *args, **kwargs):
		like = instance
		post = like.post
		sender = like.user

		notify = Notification.objects.filter(post=post, sender=sender, notification_type=1)
		notify.delete()

#Likes
post_save.connect(Likes.user_liked_post, sender=Likes)
post_delete.connect(Likes.user_unlike_post, sender=Likes)

iteractions/models/message.py
from django.db import models
from users.models import User
from django.db.models import Max

# Create your models here.
class Message(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='from_user')
	recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user')
	body = models.TextField(max_length=1000, blank=True, null=True)
	date = models.DateTimeField(auto_now_add=True)
	is_read = models.BooleanField(default=False)


	def send_message(from_user, to_user, body):
		sender_message = Message(
			user=from_user,
			sender=from_user,
			recipient=to_user,
			body=body,
			is_read=True)
		sender_message.save()
		if body != '':
			recipient_message = Message(
				user=to_user,
				sender=from_user,
				body=body,
				recipient=from_user,)
			recipient_message.save()
		return sender_message
		
	def get_messages(user):
		messages = Message.objects.filter(user=user).values('recipient').annotate(last=Max('date')).order_by('-last')
		
		users = []
		for message in messages:
			users.append({
				'user': User.objects.get(pk=message['recipient']),
				'last': message['last'],
				'unread': Message.objects.filter(user=user, recipient__pk=message['recipient'], is_read=False).count()
				})

		return users

iteractions/models/notification.py
from django.db import models
from users.models import User

# Create your models here.

class Notification(models.Model):
	NOTIFICATION_TYPES = ((1,'Like'),(2,'Comment'), (3,'Follow'))

	post = models.ForeignKey('posts.Project', on_delete=models.CASCADE, related_name="noti_post", blank=True, null=True)
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_from_user")
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="noti_to_user")
	notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
	text_preview = models.CharField(max_length=90, blank=True)
	date = models.DateTimeField(auto_now_add=True)
	is_seen = models.BooleanField(default=False)

iteractions/forms.py
from django import forms
from iteractions.models import Comment

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)

iteractions/views.py
#Django
from django.template import loader, RequestContext
from django.views.generic import TemplateView
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.contrib import messages
from django.urls import reverse

#model
from users.models import User, Profile
from iteractions.models import Relationship, Likes, Notification, Comment, Message
from posts.models import Project



# Create your views here.
@login_required
def follow(request, username, project_slug):
	current_user = request.user
	to_user = User.objects.get(username=username)
	to_user_id = to_user
	rel = Relationship(from_user=current_user, to_user=to_user_id)
	rel.save()

	notify = Notification(sender=current_user, user=to_user_id, notification_type=3)
	notify.save()
	if project_slug==username:
		return HttpResponseRedirect(reverse('users:detail', args=[username]))	
	elif project_slug==to_user.email:
		return redirect('iteractions:list_user')
	else:
		return HttpResponseRedirect(reverse('posts:detail_project', args=[project_slug, 0]))
	
@login_required
def unfollow(request, username, project_slug):
	current_user = request.user
	to_user = User.objects.get(username=username)
	to_user_id = to_user.id
	rel = Relationship.objects.filter(from_user=current_user.id, to_user=to_user_id).get()
	rel.delete()

	notify = Notification.objects.filter(sender=current_user, user=to_user_id, notification_type=3)
	notify.delete()
	if project_slug==username:
		return HttpResponseRedirect(reverse('users:detail', args=[username]))	
	elif project_slug==to_user.email:
		return redirect('iteractions:list_user')
	else:
		return HttpResponseRedirect(reverse('posts:detail_project', args=[project_slug, 0]))

@login_required
def UserListView(request,**kwargs):
    busqueda = request.POST.get("buscar")
    users = User.objects.all().order_by('username')
    if busqueda:
        users = User.objects.filter(
            Q(username__icontains = busqueda) | 
            Q(email__icontains = busqueda) 
        ).distinct()	
    paginator=Paginator(users, 8)
    page=request.GET.get('page')
    users=paginator.get_page(page)
    return render(request, 'iteractions/list_users.html', {'users':users})

@login_required
def like(request, project_id,  project_slug):
	user = request.user
	post = Project.objects.get(id=project_id)
	current_likes = post.likes
	liked = Likes.objects.filter(user=user, post=post).count()

	if not liked:
		like = Likes.objects.create(user=user, post=post)
		current_likes = current_likes + 1
	else:
		Likes.objects.filter(user=user, post=post).delete()
		current_likes = current_likes - 1
	
	post.likes = current_likes
	post.save()
	if post.url == project_slug:
		return HttpResponseRedirect(reverse('posts:detail_project', args=[project_slug, 0]))
	elif post.id == int(project_slug):
		return HttpResponseRedirect(reverse('posts:feed'))
	else:
		return HttpResponseRedirect(reverse('posts:list_project'))


@login_required
def ShowNOtifications(request):
	user = request.user
	notifications = Notification.objects.filter(user=user).order_by('-date')
	Notification.objects.filter(user=user, is_seen=False).update(is_seen=True)

	template = loader.get_template('iteractions/notifications.html')

	context = {
		'notifications': notifications,
	}

	return HttpResponse(template.render(context, request))

@login_required
def DeleteNotification(request, noti_id):
	user = request.user
	Notification.objects.filter(id=noti_id, user=user).delete()
	return redirect('iteractions:notification')


def CountNotifications(request):
	count_notifications = 0
	if request.user.is_authenticated:
		count_notifications = Notification.objects.filter(user=request.user, is_seen=False).count()
	return {'count_notifications':count_notifications}


def DeleteComments(request, comment_id, url):
	projects = Project.objects.get(url=url)
	
	comment = Comment.objects.get(id=comment_id)
	Comment.objects.filter(id=comment_id, user= comment.user, post=comment.post).delete()

	count=projects.count_comments-1
	Project.objects.filter(url=url).update(count_comments=count)
    
	return HttpResponseRedirect(reverse('posts:detail_project', args=[url, 0]))
	

@login_required
def favorite(request, post_id, position):
	user = request.user
	post = Project.objects.get(id=post_id)
	profile = Profile.objects.get(user=user)
	url=post.url

	if profile.favorites.filter(id=post_id).exists():
		profile.favorites.remove(post)

	else:
		profile.favorites.add(post)
	if position != 0:
		return HttpResponseRedirect(reverse('posts:detail_project', args=[url, 0]))
	else:
		return HttpResponseRedirect(reverse('users:detail', args=[user.username]))

@login_required
def Inbox(request, username):
	messages = Message.get_messages(user=request.user)
	active_direct = None
	directs = None

	if username != request.user.username:
		if messages:
			message = messages[0]
			active_direct = message['user'].username
			directs = Message.objects.filter(user=request.user, recipient=message['user'])
			directs.update(is_read=True)
			for message in messages:
				if message['user'].username == active_direct :
					message['unread'] = 0
	
	active_direct = User.objects.get(username=username)

	

	context = {
		'directs': directs,
		'messages': messages,
		'active_direct': active_direct,
		'username':username,

		}

	template = loader.get_template('iteractions/messages.html')

	return HttpResponse(template.render(context, request))

@login_required
def Directs(request, username):
	user = request.user
	messages = Message.get_messages(user=user)
	active_direct = User.objects.get(username=username)
	directs = Message.objects.filter(user=user, recipient__username=username)
	directs.update(is_read=True)

	for message in messages:
		if message['user'].username == username:
			message['unread'] = 0

	context = {
		'directs': directs,
		'messages': messages,
		'active_direct':active_direct,
	}

	template = loader.get_template('iteractions/messages.html')

	return HttpResponse(template.render(context, request))

@login_required
def SendDirect(request):
	from_user = request.user
	to_user_username = request.POST.get('to_user')
	body = request.POST.get('body')
	if body!='':
		if request.method == 'POST':
			to_user = User.objects.get(username=to_user_username)
			Message.send_message(from_user, to_user, body)
			return HttpResponseRedirect(reverse('iteractions:messages', args=[to_user_username]))
		else:
			HttpResponseBadRequest()
	else:
		return HttpResponseRedirect(reverse('iteractions/messages.html', args=[to_user_username]))

@login_required
def NewConversation(request, username):
	from_user = request.user
	body=''
	try:
		to_user = User.objects.get(username=username)
		
	except Exception as e:
		return redirect('iteractions:list_user')
	messages = Message.objects.filter(sender=from_user, recipient=to_user).exists()

	if not messages:
		if from_user != to_user:
			Message.send_message(from_user, to_user, body)

	return HttpResponseRedirect(reverse('iteractions:messages', args=[username]))


def DeleteConversation(request,  recipient):
	user=request.user
	Message.objects.filter(user=user, recipient= recipient).delete()
    
	return HttpResponseRedirect(reverse('iteractions:messages', args=[request.user.username]))


def checkDirects(request):
	directs_count = 0
	if request.user.is_authenticated:
		mensajes=Message.objects.filter(user=request.user, is_read=False)
		for mensaje in mensajes:
			if mensaje.body != '':
				directs_count+=1

	return {'directs_count':directs_count}


    

templates/iteractions/list_users.html
{% extends 'base.html' %}
{% load static %}
{% block head_content %}
    Usuarios | VentGram
{% endblock%}

{% block nav %}
    {% include 'nav.html' %}
{% endblock%}

{% block content %}
<section class="companies-info">
    <div class="container">
        <div class="company-title">
            <h3>Todos los usuarios de VentGram</h3>
        </div><!--company-title end-->
        <div class="companies-list">
            <div class="row">
                {% include 'posts/section_post_shear.html' %}
                {% for user in users %}
                    {% if user != request.user %}
                        <div class="col-lg-3 col-md-4 col-sm-6 col-12 mt-2">
                            <div class="company_profile_info">
                                <div class="company-up-info">
                                    {% if user.profile.picture %}
                                        <a href="{% url 'users:detail' user.username %}">
                                            <img src="{{user.profile.picture.url}}" alt="profile-image" width="90" height="90">
                                        </a>
                                    {% else %}
                                        <div class="list-user">
                                            <a href="{% url 'users:detail' user.username %}" >
                                            <span>{{user.first_name|first}}{{user.last_name|first}}</span>
                                            </a>
                                        </div>
                                    {% endif %}
                                    <h3>{{user.username}}</h3>
                                    <h4>{{user.email}}</h4>
                                    <ul>
                                        {% if request.user.is_authenticated %}
                                            {% if user != request.user %}
                                                {% if user not in request.user.profile.following %}
                                                    <li><a href="{% url 'iteractions:follow' user user.email%}" title="" class="flww"><i class="la la-plus" style="font-size: 18px;top: 1px;padding-right: 2px;"></i>Seguir</a></li>
                                                {% else %}
                                                    <li><a href="{% url 'iteractions:unfollow' user user.email%}" title="" class="flww"><i class="fas fa-check-circle" style="font-size: 18px;top: 1px;padding-right: 4px;"></i>Siguiendo</a></li>
                                                {% endif %}
                                                <li><a href="{% url 'iteractions:newconversation' user.username %}" title="" class="message-us"><i class="fa fa-envelope"></i></a></li>
                                            {% endif %}
                                        {% endif %}
                                        
                                    </ul>
                                </div>
                                <a href="{% url 'users:detail' user.username %}" title="" class="view-more-pro">Ver Perfil</a>
                            </div><!--company_profile_info end-->
                        </div>
                    {% endif %}
                {% endfor %}

                {% if users %}
                    {% include 'iteractions/pagination_user.html' %}
                {% endif %}
            </div>
        </div><!--companies-list end-->

    </div>
</section>
{% endblock %}

{% block footer %}
    {% include 'footer.html' %}
{% endblock %}

templates/iteractions/messages.html
{% extends 'posts/base.html' %}
{% block head_content %}
Messages | VentGram
{% endblock%}

{% load static %}
{% load humanize %}
<!--herencia de posts/base html estructura de cuerpo de html-->

{% block row %}
<div class="col-lg-10 offset-lg-1">
	<div id="frame">
		<div id="sidepanel">

			<!--buscar usuario
			{% if messages %}
			<div id="search" class="text-center mt-2">
				<form method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					<label for=""><i class="fa fa-search" aria-hidden="true"></i></label>
					<input type="text" name="buscar" placeholder="Buscar conversacion..." value="{{ request.POST.buscar }}" />
				</form>
			</div>
			{% endif %} -->
			
			<!--Mostrar contactos de mensajes-->
			<div id="contacts" class="mt-3">
				<ul style="margin-right: 0px;">
					{% if not messages%}
					<div class="text-center mt-3">
						<span style="color: white;">No existen conversaciones</span>
					</div>
					
					{%else%}
					{% for message in messages %}
						<a class="{% if active_direct == message.user.username %}is-active{% endif %}"
							href="{% url 'iteractions:directs' message.user.username%}">
							<li class="contact">
								<div class="wrap">
									<span class="contact-status online"></span>
									{% if message.user.profile.picture %}
									<img src="{{ message.user.profile.picture.url }}" alt="profile-image" width="37"
										height="37">
									{% else %}
									<div class="like-coms-chat" >
										<h2>{{message.user.first_name|first}}{{message.user.last_name|first}}</h2>
									</div>
									{% endif %}
									<div class="meta">
										<p class="name" style="color: white;">{{message.user.first_name}} {{message.user.last_name}}</p>
										{% if message.unread %}
										<p class="preview" style="font-weight: normal; color: rgb(255, 255, 255);"><i
												class="fas fa-comment-dots"></i> {{ message.unread }} Mensajes nuevos...</p>
										{% endif %}
									</div>
								</div>
							</li>
						</a>
					{% endfor %}
					{%endif%}
				</ul>
			</div>

			<!--Nueva conversacion-->
			<div id="bottom-bar">
				<a href="{% url 'iteractions:list_user' %}">
					<button id="addcontact"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> <span>Nuevo mensaje</span></button>
				</a>
			</div>
		</div>
		{% if request.user.username != username %}
		<div class="content">
			<div class="contact-profile">
				{% if active_direct.profile.picture %}
				<a href="{% url 'users:detail' active_direct.username %}"><img src="{{ active_direct.profile.picture.url }}" alt="profile-image" width="37" height="37"></a> 
				{% else %}
				<a href="{% url 'users:detail' active_direct.username %}"> 
					<div class="like-coms">
						<span
							class="mt-2 ml-2 mr-2">{{active_direct.first_name|first}}{{active_direct.last_name|first}}</span>
					</div>
				</a> 
				{% endif %}
				<a href="{% url 'users:detail' active_direct.username %}"><p style="margin-top: 15px;">{{active_direct.first_name}} {{active_direct.last_name}}</p></a>
				<div class="ed-opts">
					<a href="" title="" class="ed-opts-open pr-3 pt-1" ><i class="la la-ellipsis-v"></i></a>
					<ul class="ed-options" style="top: 82%; height: 40px; line-height: 0px; background-color:rgba(235, 19, 19, 0.747);">
							<li><a href="{% url 'iteractions:delete_conversation' active_direct.id %}" title="Eliminar" style="color: white;">Eliminar Chat</a></li>
					</ul>
				</div>
				<div class="social-media">
					{% if active_direct.profile.facebook %}
					<a href="{{ active_direct.profile.facebook }}" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a> 
					{% endif %}
					{% if active_direct.profile.twitter %}
					<a href="{{ active_direct.profile.twitter }}" target="_blank"><i class="fa fa-twitter" aria-hidden="false"></i></a> 
					{% endif %}
					{% if active_direct.profile.linkedin %}
					<a href="{{ active_direct.profile.linkedin }}" target="_blank" style="color: rgb(0, 123, 182);"><i class="fa fa-linkedin" aria-hidden="true"></i></a> 
					{% endif %}
					{% if active_direct.profile.github %}
					<a href="{{ active_direct.profile.github }}" target="_blank" style="color: rgb(77, 77, 77);"><i class="fa fa-github" aria-hidden="true"></i></a>
					{% endif %}
					
				</div>

			</div>
			<!--Mostrar mensaje-->
			<div class="messages">
				<ul>
					
					{% for direct in directs %}
						{% if direct.body != '' %}
						{% if direct.sender == request.user %}
							<li class="replies text-right mb-0" >
								<p class="ml-1 ">{{direct.body}}</p>
							</li>
							<li class="mt-0 pt-0">
								<div class="date text-right mr-2">
									<h2>{{ direct.date|naturaltime }}</h2>
								</div>
							</li>
						{% else %}
							<li class="sent">
								<p>{{direct.body}}</p>
								<div class="date">
									<h1 class="ml-2">{{ direct.date|naturaltime }}</h1>
								</div>
							</li>
						{% endif %}

						{% endif %}
					{% endfor %}
				</ul>
			</div>

			<!--Enviar mensaje-->
			<form role="form" method="POST" action="{% url 'iteractions:send-direct' %}">
				{% csrf_token %}
				<div class="message-input">
					<div class="wrap">
						<input type="hidden" name="to_user" value="{{ active_direct }}" />
						<textarea name="body" placeholder="Escribe un mensaje..." ></textarea>
						<button type="submit" name="action"><i class="fa fa-paper-plane"
								aria-hidden="true"></i></button>
					</div>
				</div>
			</form>
		</div>
		{% else %}
		<div class="content">
			<div class="contimg">
				<div class="text-center">
					<h1>Inicia una <br> conversación</h1>
				</div>
				<img src="{% static 'img/Logo_VG.png' %}">
				<img src="{% static 'img/cm-main-img.png' %}" style="filter: hue-rotate(900deg);" >	
			</div>
			
		</div>
		{% endif %}
	</div>
</div>
{% endblock %}

templates/iteractions/notifications.html
{% extends 'posts/base.html' %}
{% block head_content %}
Notifications | VentGram
{% endblock%}
{% load static %}
{% load humanize %}
<!--herencia de posts/base html estructura de cuerpo de html-->

{% block other_top %}
<!--agregar vistas al inicio sin ningun contenedor puesto -->
{% endblock %}

{% block row %}
<div class="col-lg-6 offset-lg-3">
    <div class="acc-setting">
        {% if notifications %}
            <h3>Notificaciones</h3>
            {% else %}
            <h3 class="text-center">No existen notificaciones</h3>
        {% endif %}
        <div class="notifications-list">

            {% for notification in notifications %}
                {% if notification.sender.profile.user != request.user %}
                <div class="notfication-details">
                    <a href="{% url 'iteractions:delete-notification' notification.id %}" style="color:#4e4e4e; float: right;"><i class="fas fa-times-circle"></i></a>
                    <div class="notification-info">
                        <a href="{% url 'users:detail' notification.sender.profile.user.username  %}" class="usy-dt">
                            {% if notification.sender.profile.picture %}
                                <img src="{{ notification.sender.profile.picture.url }}" alt="profile-image" width="37" height="37">
                            {% else %}
                            <div class="like-coms">
                                <span class="mt-0">{{notification.sender.profile.user.first_name|first}}{{notification.sender.profile.user.last_name|first}}</span>
                            </div>
                            {% endif %}
                            </a>        
                        <div class="ml-5">
                            {% if notification.notification_type == 1 %}
                                <h3><a 
                                    href="{% url 'users:detail' notification.sender.profile.user.username  %}">
                                    {{ notification.sender.profile.user.first_name}} {{ notification.sender.profile.user.last_name}}
                                    </a> @{{ notification.sender.profile.user.username }}
                                </h3>
                                <h3><i class="fas fa-heart mr-1" style="color: rgb(231, 71, 71);"></i>Indicó que le gusta tu proyecto.</h3>
                                <h3><a href="{% url 'posts:detail_project' notification.post.url 0 %}">{{ notification.post.title}} </a></h3>
                            {% endif %}

                            {% if notification.notification_type == 2 %}
                                <h3><a href="{% url 'users:detail' notification.sender.profile.user.username  %}">{{ notification.sender.profile.user.first_name}} {{ notification.sender.profile.user.last_name}}
                                </a> @{{ notification.sender.profile.user.username }}</h3>
                                <h3><i class="fas fa-comment-alt mr-1" style="color: rgb(39, 145, 231);"></i>Comento tu proyecto.</h3>
                                <h3><a href="{% url 'posts:detail_project' notification.post.url 0 %}">{{ notification.post.title}}</a></h3>
                            {% endif %}

                            {% if notification.notification_type == 3 %}
                                <h3><a href="{% url 'users:detail' notification.sender.profile.user.username  %}">{{ notification.sender.profile.user.first_name}} {{ notification.sender.profile.user.last_name}}</a> @{{notification.sender.profile.user.username}}</h3>
                                <h3><i class="fas fa-user-plus mr-1 " style="color: #53d690;"></i>Te siguió</a></h3>
                            {% endif %}

                                <h3 style="font-weight: 600; color:rgb(182, 182, 182); font-size: 12px;">{{ notification.date|naturaltime }}</h3>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        <!--notifications-list end-->
    </div>
    <!--acc-setting end-->
</div>
{% endblock %}


{% block other_button %}
<!--agregar vistas al final sin ningun contenedor puesto -->

{% endblock %}

<!--herencia de posts/base html estructura de cuerpo de html-->