VentGram/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views
from posts import views
from iteractions import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('iteractions/', include(('iteractions.urls', 'iteractions'), namespace='iteractions')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iteractions/urls.py
#Django
from django.urls import path


#importaciones de apps
from iteractions import views


urlpatterns = [
        
    path(
        route='follow/<str:username>/<str:project_slug>/',
        view=views.follow,
        name='follow',
        ),

    path(
        route='unfollow/<str:username>/<str:project_slug>/',
        view=views.unfollow,
        name='unfollow',
        ),

    path(
        route='list_user/',
        view=views.UserListView,
        name='list_user',
        ),

    path(
        route='<int:project_id>/<str:project_slug>/',
        view=views.like,
        name='like_project'
        ),

    path(
        route='<int:post_id>/<int:position>',
        view=views.favorite,
        name='post_favorite'
        ),
        
    path(
        route='notification/',
        view=views.ShowNOtifications,
        name='notification'
        ),
    
    path(
        route='<noti_id>/delete',
        view=views.DeleteNotification,
        name='delete-notification'
        ),

    path(
        route='<int:comment_id>/<str:url>/delete',
        view=views.DeleteComments,
        name='delete-comments'
        ),

    path(
        route='messages/<str:username>',
        view=views.Inbox,
        name='messages'
        ),

    path(
        route='messages/directs/<username>',
        view=views.Directs,
        name='directs'
        ),

    path(
        route='messages/send/',
        view=views.SendDirect, 
        name='send-direct'
        ),

    path(
        route='messages/new/<username>',
        view=views.NewConversation, 
        name='newconversation'
        ),

    path(
        route='delete/<recipient>',
        view=views.DeleteConversation, 
        name='delete_conversation'
        ),

]

posts/urls.py
#Postss Urls

#Django
from django.urls import path


#importaciones de apps
from posts import views

urlpatterns = [

    #managment

    path(
        route='',
        view=views.PostHomeView,
        name='home'
        ),
        
    path(
        route='posts/',
        view=views.ProjectFeedView,
        name='feed'
        ),

    path(
        route='posts/projects',
        view=views.FilterProjectView,
        name='list_project'
        ),

    path(
        route='posts/create_project',
        view=views.CreatedProjectView.as_view(),
        name='new_project'
        ), 

    path(
        route='posts/<slug:url>/project1<int:project_id>48/',
        view=views.ProjectDetailView,
        name='detail_project'
        ),

    path(
        route='update_project/<slug:url>/',
        view=views.UpdateProjectView.as_view(),
        name='update_project'
        ),

    path(
        route='delete_project/<slug:url>/',
        view=views.ProjectDeleteView.as_view(),
        name='delete_project'
    ),
        
]

users/urls.py
#Users Urls

#Django
from django.urls import path


#importaciones de apps
from users import views

urlpatterns = [

    #managment 
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login',
        ),
        
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout',
        ),

    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup',
        ),

    path(
        route='validate/',
        view=views.validate_token,
        name='validate_token',
        ),
    
    path(
        route='me/update_profile/',
        view=views.UpdateProfileView.as_view(),
        name='update_profile'
        ),

    path(
        route='me/add_social_net/',
        view=views.UpdateSocialNet.as_view(),
        name='social_net'
        ),

    path(
        route='me/update_user/',
        view=views.UpdateUserView.as_view(),
        name='update_user'
        ),
        
    path(
        route='me/update_password/', 
        view=views.UserChangePasswordView.as_view(),
        name='change_password'
        ),

    path(
        route='me/delete_account/', 
        view=views.UserDelete.as_view(),
        name='delete_user'
        ),


    #profile
    path(
        route='<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    #Ajax
    path(
        route='ajax/provinces/',
        view=views.load_province,
        name='ajax_load_province'
    ),

        path(
        route='ajax/city/',
        view=views.load_city,
        name='ajax_load_city'
    ),

]

templates/account_setting.html
{% extends 'base.html' %}
{% load static %}
{% block head_content %}

{% endblock%}

{% block nav %}
    {% include 'nav.html' %}
{% endblock %}

{% block content %}
<section class="profile-account-setting">
    <div class="container">
        <div class="account-tabs-setting">
            <div class="row">
                <div class="col-lg-12">
                    {% if messages %}
                    <div class="messages alert alert-success">
                        {% for message in messages %}
                        <h2>{{ message }} </h2>
                        {% endfor %}
                    </div>
                    {% endif %}

                </div>
                
                <div class="col-lg-3">
                    <div class="acc-leftbar">
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a href="{% url 'users:update_profile' %}"><i class="fas fa-id-badge"></i>Perfil</a>
                            <a href="{% url 'users:update_user' %}"><i class="far fa-user"></i>Usuario</a>
                            <a href="{% url 'users:change_password' %}"><i class="fa fa-lock"></i>Cambiar contraseña</a>
                            <a href="{% url 'users:social_net' %}"><i class="fas fa-globe-americas"></i>Redes Sociales</a>
                            <a href="{% url 'users:delete_user' %}" ><i class="fa fa-random"></i>Eliminar Cuenta</a>
                        </div>
                    </div><!--acc-leftbar end-->
                </div>
                <div class="col-lg-9">
                    {% block profile %}{% endblock %}

                    {% block user %}{% endblock %}

                    {% block password %}{% endblock %}

                    {% block redes %}{% endblock %}
                      
                    {% block deactivate %}{% endblock %}
            </div>
        </div><!--account-tabs-setting end-->
    </div>
</section>

{% endblock %}
{% block footer %}
  {% include 'footer.html' %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block head_content %}{% endblock%}
    </title>
    
    <!-- Bootstrap CSS fontawesome-->
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'img/Logo_color.png' %}" />
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/chat.css' %}" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.range.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/line-awesome-font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/slick/slick-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">


</head>

<body>
    
    <div class="wrapper">
    <!--Nav -->
        <header>
            
            {% block nav %}
            {% endblock%}
            
        </header>
    <!--Nav -->

    <!--Contenido-->
    <div class="cuerpo">
        {% block content %}

        {% endblock %}
    </div>

    <!--Contenido-->

    <!--footer-->
    {% block footer %}
    {% endblock %}
    <!--footer-->
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- Vue JS --> 
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/preview.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/slick/slick.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/scrollbar.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/footer.html
{% load static %}
<footer>
  <div class="footy-sec mn no-margin">
    <div class="container text-center">
      <ul>
        <li><a href="" title="">Centro de ayuda</a></li>
        <li><a href="" title="">Principios de la comunidad</a></li>
        <li><a href="" title="">Politicas de privacidad</a></li>
        <li><a href="" title="">Politicas de derecho de autor</a></li>
        <li><a href="" title="">Politicas de cookies</a></li>
      </ul>
      <p><img src="{% static 'img/copy-icon2.png' %}" alt="Copyright">Copyright 2021</p>
      <img class="fl-rgt" src="{% static 'img/footerlogo.png' %}" alt="">
    </div>
  </div>
</footer>

templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% load static %}
        <title>Home - VentGram</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/img/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {% static 'css/styles-home.css' %}" rel="stylesheet" />

    </head>
    
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"> <img src="/static/img/Logo_col.png" width="200px" height="50px" alt=""></a>
               
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">Acerca de</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#services">Servicios</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#portfolio">Portafolio</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#contact">Contacto</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'users:login' %}">Iniciar Sesión</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">
                            Crece de una manera más sencilla, rápida y eficiente</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">VentGram es una herramienta muy importante para emprender en una idea de negocio o proyectos tecnológicos que tengan como fin satisfacer una necesidad, demanda o servicio!</p>
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'users:signup' %}">Registrate</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="page-section bg-primary" id="about">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">¡Lo que necesitas!</h2>
                        <hr class="divider light my-4" />
                        <p class="text-white-50 mb-4">VentGram tiene lo que necesita para poder impulsar tus proyectos de emprendimientos, tener una comunicación directa con interesados. Siendo una herramienta muy fácil de usar!</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
                <h2 class="text-center mt-0">Servicios que ofrece VentGram</h2>
                <hr class="divider my-4" />
                <div class="row">
                    <div class="col-lg-4 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-laptop-code text-primary mb-4"></i>
                            <h3 class="h4 mb-2">A hoy</h3>
                            <p class="text-muted mb-0">Todos los proyectos se mantienen actualizados para mantener las cosas frescas.</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-globe text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Listo para publicar</h3>
                            <p class="text-muted mb-0">Puedes publicar tu proyecto cuando quieras y realizar cambios.</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 text-center">
                        <div class="mt-5">
                            <i class="fas fa-4x fa-envelope text-primary mb-4"></i>
                            <h3 class="h4 mb-2">Mensajería privada</h3>
                            <p class="text-muted mb-0">Mantente comunicado con otros usuarios de Ventgram gracias al chat.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Portfolio-->
        <div id="portfolio">
            <div class="container-fluid p-0">
                <h2 class="text-center mt-0">Proyectos</h2>
                <hr class="divider my-4" />
                <div class="row no-gutters">
                    {% for project in projects %}
                    <div class="col-lg-4 col-sm-6">
                        <a class="portfolio-box" href="{% url 'users:signup' %}">
                            <img class="img-fluid" src="{{ project.image.url }}" alt="" />
                            <div class="portfolio-box-caption">
                                <div class="project-category text-white-50">{{ project.category }}</div>
                                <div class="project-name">{{ project.title }}</div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Call to action-->

        <!-- Contact-->
        <section class="page-section" id="contact">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="mt-0">¡Mantengámonos en contacto!</h2>
                        <hr class="divider my-4" />
                        <p class="text-muted mb-5">¿Listo para comenzar tu proyecto con nosotros? ¡Llámanos o envíanos un correo electrónico y nos pondremos en contacto para ayudarte con cualquier inquietud!</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                        <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                        <div>+593 985 739 457</div>
                    </div>
                    <div class="col-lg-4 mr-auto text-center">
                        <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                        <!-- Make sure to change the email address in BOTH the anchor text and the link target below!-->
                        <a class="d-block" href="mailto:ventgram@gmail.com"> ventgram@gmail.com</a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted">Copyright © 2021 - VentGram</div></div>
        </footer>

        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->

        <script src="{% static 'js/home.js' %}"></script>
    </body>
</html>

templates/nav.html
{% load static %}
<div class="container">
  <div class="header-data">
    <div class="logo">
      <a href="{% url 'posts:feed' %}" title=""><img src="{% static 'img/Logo_col.png' %}" width="200px" height="50px" alt=""></a>
    </div><!--logo end-->
    <div class="menu-btn">
      <a href="#" title=""><i class="fa fa-bars"></i></a>
    </div><!--menu-btn end-->
    <div id="iteraction" class="user-account">
      <div class="user-info mr-0">
        {% if request.user.profile.picture %}
          <a type="button" class="mt-0 ml-2">
            <img src="{{ request.user.profile.picture.url }}" alt="profile-image">
          </a>
          {% else %}
          <a class="like-coms mt-0 ml-1" type="button">
              <span style="margin-top: 0px;">{{request.user.first_name|first}}{{request.user.last_name|first}}</span>
          </a>
        {% endif %}
      </div>
      <div class="user-account-settingss" id="users">
        <ul class="on-off-status">
          <li>
            <a href="{% url 'users:detail' request.user.username %}">
              <div class="usy-dt mr-2">
                  {% if request.user.profile.picture %}
                    <img src="{{ request.user.profile.picture.url }}" class="ml-2 my-2" alt="profile-image" width="37" height="38">
                  {% else %}
                  <div class="like-coms ml-3">
                      <span>{{request.user.first_name|first}}{{request.user.last_name|first}}</span>
                  </div>
                  {% endif %}
              </div>

                <div class="fgt-sec py-2">
                  <h6 class="pt-1 ">{{request.user.username|capfirst}}</h6>
                  <p class="mb-1" style="line-height:18px;">Ver mi perfil</p>
              </div>
              </a>
          </li>
          </ul>

        <h3>Ajustes</h3>
        <ul class="us-links">
          <li><a href="{% url 'users:update_profile' %}" title="Configuracion de Cuenta"><i class="fas fa-id-badge mr-2"></i>Editar Perfil</a></li>
        </ul>
        <ul class="us-links">
          <li><a href="{% url 'users:update_user' %}" title="Configuracion de Cuenta"><i class="far fa-user mr-2"></i>Editar Usuario</a></li>
        </ul>
        <ul class="us-links">
          <li><a href="{% url 'users:social_net' %}" title="Configuracion de Cuenta"><i class="fas fa-globe-americas mr-2"></i>Redes Sociales</a></li>
        </ul>
        <ul class="us-links">
          <li><a href="{% url 'users:change_password' %}" title="Configuracion de Cuenta"><i class="fa fa-lock mr-2"></i>Cambiar Contraseña</a></li>
        </ul>
        <h3 class="tc"><a href="{% url 'users:logout' %}" title="Cerrar Sesion"><i class="fas fa-power-off mr-2"></i>Cerrar Sesion</a></h3>
      </div><!--user-account-settingss end-->
    </div>
    <nav>
      <ul>
        <li>
          <a href="{% url 'posts:feed' %}" title="">
            <span><img src=" {% static 'img/icon1.png' %}" alt=""></span>
            Inicio
          </a>
        </li>
        <li>
          <a href="{% url 'posts:list_project' %}" title="">
            <span><img src="{% static 'img/icon3.png' %}" alt=""></span>
            Proyectos
          </a>
        </li>
        <li>
          <a href="{% url 'iteractions:list_user' %}" title="">
            <span><i class="fas fa-users" style="font-size: 17px;"></i></span>
            Usuarios
          </a>
        </li>
        <li>
          <a href="{% url 'users:detail' request.user.username %}" title="Perfil">
            <span><img src="{% static 'img/icon4.png' %}" alt=""></span>
            Perfil
          </a>
        </li>
        <li>
          <a href="{% url 'iteractions:messages' request.user.username %}" title="" class="not-box-openm">
            <span><img src="{% static 'img/icon6.png' %}" alt="">              
              {% if directs_count %}
                <span class="spans">{{directs_count}}</span>
              {% endif %}
            </span>
            Mensajes
          </a>
        </li>
        <li>
          <a href="{% url 'iteractions:notification' %}" title="Notificaciones">
            <span><img src="{% static 'img/icon7.png' %}">
              {% if count_notifications %}
                <span class="spans">{{ count_notifications }}</span>
              {% endif %}
          </span>
            Notificaciones

          </a>
          <div class="notification-box noti" id="notification">
            <div class="nt-title">
              <h4>Setting</h4>
              <a href="#" title="">Clear all</a>
            </div>
            <div class="nott-list">
                <div class="view-all-nots">
                  <a href="{% url 'iteractions:notification' %}" title="">
                    {% if count_notifications %}
                      {{ count_notifications }}
                    {% endif %}
                  </a>
                </div>
            </div><!--nott-list end-->
          </div><!--notification-box end-->
        </li>
      </ul>
      
    </nav><!--nav end-->

  </div><!--header-data end-->

</div>

templates/pagination.html
<div class="col-12 text-center">
    {% if projects.has_previous %}

    <a class="btn btn-danger" href="?page={{ projects.previous_page_number }}">
        Anterior
    </a>

    {% endif %}

    <a class="btn btn-danger" href="#">
        {{ projects.number }} de {{ projects.paginator.num_pages }}
    </a>

    {% if projects.has_next %}

    <a class="btn btn-danger" href="?page={{ projects.next_page_number }}">
        Siguiente
    </a>
    {% endif %}
</div>